spring:
  datasource:
    url: jdbc:sqlserver://ncp-db-server.database.windows.net:1433;database=ncp-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: peakycoders
    password: Password123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191
